version: "3"

services:
  app:
    container_name: app_name_app
    build: .
    volumes:
      - .:/app_name
    ports:
      - 3000:3000
    depends_on:
      - db


  db:
    image: postgres:10.1
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"
